@baseURL = https://localhost:7206
@host = http://localhost
@port = 5139
@baseUrl = {{host}}:{{port}}


GET {{baseURL}}/api/WeatherForecast/2/allweather?max=33&min=-22
Accept: application/json


###

POST {{baseURL}}/api/weatherforecast/Generate?count=4
Content-Type: application/json

{
  "min":-22,
  "max":33
}

###
