@baseURL = https://localhost:7206

GET {{baseURL}}/api/restaurants

###

GET {{baseURL}}/api/restaurants/2002 

###

POST {{baseURL}}/api/restaurants
Content-Type: application/json
{
  "Name": "d",
  "Category":"Italian",
  "Description":"New Description"
}

###

DELETE {{baseURL}}/api/restaurants/1002

###

PATCH {{baseURL}}/api/restaurants/2002
Content-Type: application/json

{
  "Name": "ddd",
  "Description":"New Description222",
  "HasDelivery":true
}

###
