@baseURL = https://localhost:7206
@token = CfDJ8GadAzmW3mlJh06rLi7m0YkdgmEbAnlAgjH0p_QwQyfIkjAfF4pyPOkPK8uFwfSmgAkNL2Gav6J0W-Sw6IhFX_cs8xnq-GXS4QqDlbhUZ23h0wDjOBXEdS0C3q81Nm7ZurdruEoMaQAvs1nQ7UkgRDGhLIXvQ6OXqx4IUXjNK3DbT_UyR1vmpjv9-tKxJG5j-uW0-A50DyWmBm_t4WJePWQF8X8jHRtgPQtYx1JrU-cSvIRbJO6BYNZW8L_65npgr21Oe_3uYraCmvsivq4OjTkrD7vYCzSOr9ECf9IDMzwrPcnYyJ8AU253gdG7y4lE9xEEn9kDCRLSvGIUi8urEtWNZGK2eh8DTSHta66VsVq6vJIDNipbSx2SsORE8zBzPyL4G2dDYZHmqh7HzoX_oYiify2adYfVDEOOMoO7vVt3BTa2IR9E3ly5hg1babMvAtunYjP1SRH8ys09HDKg3Pk7umrkJ06YDuNc3sUIqtxA9Dfg-yND3ini5MUxNFtBfBHohcwC9HqTh7WGARZK7khFINVxP4ZO_7ro4tiTHAaNTvWJgfo_yVqYxjzI9xke9TryCVWNT1Cp43YGDB-jg-GiXCShJKNcVzJXmIC2EGgk2MgvDOXpVTUfhGrJ-01d5dUPm1FKE6OQsk00YNZhFEOunqWuAkpifHjA8kzQIaLcX3dUE4ruOvoFFRsRpskuEC0dKxVG5LHbnOTfVpo4r-_IlCZgBAEAE5niGNFGUZL8MRTY2eVZNedA_Scnyt1X5NKlvpLIT_-i6kDOsq6AiW0
  

GET {{baseURL}}/api/restaurants
Authorization: Bearer {{token}}
###

GET {{baseURL}}/api/restaurants/2
Authorization: Bearer {{token}}

###

POST {{baseURL}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "Name": "Restaurant created by owner",
    "Category":"Italian",
    "Description":"New Description"
}

###

#DELETE {{baseURL}}/api/restaurants/2
#Authorization: Bearer {{token}}
###

PATCH {{baseURL}}/api/restaurants/2
Content-Type: application/json

{
  "Name": "ddd22",
  "Description":"New Description222",
  "HasDelivery":true
}

###

POST {{baseURL}}/api/restaurant/2/dishes
Content-Type: application/json
{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

GET {{baseURL}}/api/restaurant/1/dishes

###

GET {{baseURL}}/api/restaurant/1/dishes/1

###

DELETE {{baseURL}}/api/restaurant/2/dishes

###

POST {{baseURL}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password1!"
}

###

POST {{baseURL}}/api/identity/login
Content-Type: application/json

{
    "email": "testuser2@test.com",
    "password": "Password1!"
}

###

PATCH {{baseURL}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "DateOfBirth":"1980-01-01",
  "Nationality":"British"
}

###
