@baseURL = https://localhost:7206

GET {{baseURL}}/api/restaurants

###

GET {{baseURL}}/api/restaurants/1 

###

POST {{baseURL}}/api/restaurants
Content-Type: application/json
{
  "Name": "New Restaurant",
  "Category":"Italian",
  "Description":"New Description"
}

###

DELETE {{baseURL}}/api/restaurants/1002

###
